export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_CART: "REMOVE_CART",
    FETCH_PRODUCTS: "FETCH_PRODUCTS"
}